-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 11:01:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pf_airports
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pf_airports` ;

-- -----------------------------------------------------
-- Schema pf_airports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pf_airports` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `pf_airports` ;

-- -----------------------------------------------------
-- Table `pf_airports`.`dim_airlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_airports`.`dim_airlines` ;

CREATE TABLE IF NOT EXISTS `pf_airports`.`dim_airlines` (
  `IATA_CODE` TEXT NULL DEFAULT NULL,
  `AIRLINE` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;


-- -----------------------------------------------------
-- Table `pf_airports`.`dim_airports_destination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_airports`.`dim_airports_destination` ;

CREATE TABLE IF NOT EXISTS `pf_airports`.`dim_airports_destination` (
  `IATA_CODE` VARCHAR(100) NULL DEFAULT NULL,
  `AIRPORT` TEXT NULL DEFAULT NULL,
  `CITY` TEXT NULL DEFAULT NULL,
  `STATE` TEXT NULL DEFAULT NULL,
  `COUNTRY` TEXT NULL DEFAULT NULL,
  `LATITUDE` DOUBLE NULL DEFAULT NULL,
  `LONGITUDE` DOUBLE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;


-- -----------------------------------------------------
-- Table `pf_airports`.`dim_airports_origen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_airports`.`dim_airports_origen` ;

CREATE TABLE IF NOT EXISTS `pf_airports`.`dim_airports_origen` (
  `IATA_CODE` TEXT NULL DEFAULT NULL,
  `AIRPORT` TEXT NULL DEFAULT NULL,
  `CITY` TEXT NULL DEFAULT NULL,
  `STATE` TEXT NULL DEFAULT NULL,
  `COUNTRY` TEXT NULL DEFAULT NULL,
  `LATITUDE` DOUBLE NULL DEFAULT NULL,
  `LONGITUDE` DOUBLE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;


-- -----------------------------------------------------
-- Table `pf_airports`.`dim_cancellation_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_airports`.`dim_cancellation_codes` ;

CREATE TABLE IF NOT EXISTS `pf_airports`.`dim_cancellation_codes` (
  `CANCELLATION_REASON` VARCHAR(100) NULL DEFAULT NULL,
  `CANCELLATION_DESCRIPTION` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;


-- -----------------------------------------------------
-- Table `pf_airports`.`fact_airline_delay_cause`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_airports`.`fact_airline_delay_cause` ;

CREATE TABLE IF NOT EXISTS `pf_airports`.`fact_airline_delay_cause` (
  `Anio` VARCHAR(100) NULL DEFAULT NULL,
  `Mes` VARCHAR(100) NULL DEFAULT NULL,
  `carrier` VARCHAR(100) NULL DEFAULT NULL,
  `carrier_name` VARCHAR(100) NULL DEFAULT NULL,
  `airport` VARCHAR(100) NULL DEFAULT NULL,
  `airport_name` VARCHAR(100) NULL DEFAULT NULL,
  `arr_flights` VARCHAR(100) NULL DEFAULT NULL,
  `arr_del15` VARCHAR(100) NULL DEFAULT NULL,
  `carrier_ct` VARCHAR(100) NULL DEFAULT NULL,
  `weather_ct` VARCHAR(100) NULL DEFAULT NULL,
  `nas_ct` VARCHAR(100) NULL DEFAULT NULL,
  `security_ct` VARCHAR(100) NULL DEFAULT NULL,
  `late_aircraft_ct` VARCHAR(100) NULL DEFAULT NULL,
  `arr_cancelled` VARCHAR(100) NULL DEFAULT NULL,
  `arr_diverted` VARCHAR(100) NULL DEFAULT NULL,
  `arr_delay` VARCHAR(100) NULL DEFAULT NULL,
  `carrier_delay` VARCHAR(100) NULL DEFAULT NULL,
  `weather_delay` VARCHAR(100) NULL DEFAULT NULL,
  `nas_delay` VARCHAR(100) NULL DEFAULT NULL,
  `security_delay` VARCHAR(100) NULL DEFAULT NULL,
  `late_aircraft_delay` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;


-- -----------------------------------------------------
-- Table `pf_airports`.`fact_flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_airports`.`fact_flights` ;

CREATE TABLE IF NOT EXISTS `pf_airports`.`fact_flights` (
  `Anio` VARCHAR(100) NULL DEFAULT NULL,
  `Mes` VARCHAR(100) NULL DEFAULT NULL,
  `Dia` VARCHAR(100) NULL DEFAULT NULL,
  `DAY_OF_WEEK` VARCHAR(100) NULL DEFAULT NULL,
  `AIRLINE` VARCHAR(100) NULL DEFAULT NULL,
  `FLIGHT_NUMBER` VARCHAR(100) NULL DEFAULT NULL,
  `TAIL_NUMBER` VARCHAR(100) NULL DEFAULT NULL,
  `ORIGIN_AIRPORT` VARCHAR(100) NULL DEFAULT NULL,
  `DESTINATION_AIRPORT` VARCHAR(100) NULL DEFAULT NULL,
  `SCHEDULED_DEPARTURE` VARCHAR(100) NULL DEFAULT NULL,
  `DEPARTURE_TIME` VARCHAR(100) NULL DEFAULT NULL,
  `DEPARTURE_DELAY` VARCHAR(100) NULL DEFAULT NULL,
  `TAXI_OUT` VARCHAR(100) NULL DEFAULT NULL,
  `WHEELS_OFF` VARCHAR(100) NULL DEFAULT NULL,
  `SCHEDULED_TIME` VARCHAR(100) NULL DEFAULT NULL,
  `ELAPSED_TIME` VARCHAR(100) NULL DEFAULT NULL,
  `AIR_TIME` VARCHAR(100) NULL DEFAULT NULL,
  `DISTANCE` VARCHAR(100) NULL DEFAULT NULL,
  `WHEELS_ON` VARCHAR(100) NULL DEFAULT NULL,
  `TAXI_IN` VARCHAR(100) NULL DEFAULT NULL,
  `SCHEDULED_ARRIVAL` VARCHAR(100) NULL DEFAULT NULL,
  `ARRIVAL_TIME` VARCHAR(100) NULL DEFAULT NULL,
  `ARRIVAL_DELAY` VARCHAR(100) NULL DEFAULT NULL,
  `DIVERTED` VARCHAR(100) NULL DEFAULT NULL,
  `CANCELLED` VARCHAR(100) NULL DEFAULT NULL,
  `CANCELLATION_REASON` VARCHAR(100) NULL DEFAULT NULL,
  `AIR_SYSTEM_DELAY` VARCHAR(100) NULL DEFAULT NULL,
  `SECURITY_DELAY` VARCHAR(100) NULL DEFAULT NULL,
  `AIRLINE_DELAY` VARCHAR(100) NULL DEFAULT NULL,
  `LATE_AIRCRAFT_DELAY` VARCHAR(100) NULL DEFAULT NULL,
  `WEATHER_DELAY` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
